version: '3.8'

services:
  linky:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ${MARKDOWN_DIR:-./markdown}:/data/markdown
    environment:
      - MARKDOWN_DIR=/data/markdown
    restart: unless-stopped
